In [3]:
import pandas as pd

In [4]:
data= {'Students': ['Ahmad','Qaiyim','Intan','Fatehah','Akmal'], 'Marks': [85,None,45,None,67]}

In [5]:
df=pd.DataFrame(data)
print('Original Data')
df

Original Data

  Students  Marks
0    Ahmad   85.0
1   Qaiyim    NaN
2    Intan   45.0
3  Fatehah    NaN
4    Akmal   67.0

In [6]:
print('Missing Data')
print('Number of missing data: ', df.isnull().sum())

Missing Data
Number of missing data:  Students    0
Marks       2
dtype: int64

In [7]:
avg_marks=df['Marks'].mean()
print(avg_marks)

65.66666666666667

In [8]:
df.fillna(avg_marks, inplace=True)

In [9]:
print('after fillna() call()')
df

after fillna() call()

  Students      Marks
0    Ahmad  85.000000
1   Qaiyim  65.666667
2    Intan  45.000000
3  Fatehah  65.666667
4    Akmal  67.000000

# How we will use in our project

In [10]:
# fillna example
students_data= {'Name': ['Ahmad','Qaiyim','Intan','Fatehah','Akmal'], 
       'Marks': [85,None,45,None,67]}

df=pd.DataFrame(students_data)
print('Original Data')
print(df)
print('Missing Data')
print('Number of missing data: ', df.isnull().sum())
df.fillna(avg_marks, inplace=True)

Original Data
      Name  Marks
0    Ahmad   85.0
1   Qaiyim    NaN
2    Intan   45.0
3  Fatehah    NaN
4    Akmal   67.0
Missing Data
Number of missing data:  Name     0
Marks    2
dtype: int64

# Dropna() example

In [11]:
data= {'Students': ['Ahmad','Qaiyim','Intan','Fatehah','Akmal'], 'Marks': [85,None,45,None,67]}
df=pd.DataFrame(data)
print('Original Data')
df

Original Data

  Students  Marks
0    Ahmad   85.0
1   Qaiyim    NaN
2    Intan   45.0
3  Fatehah    NaN
4    Akmal   67.0

In [12]:
df=df.dropna(subset=['Marks'])
print('Dataset after dropna()')
df

Dataset after dropna()

  Students  Marks
0    Ahmad   85.0
2    Intan   45.0
4    Akmal   67.0

In [13]:
data= {'Students': ['Ahmad','Qaiyim','Intan','Fatehah','Akmal'], 'Marks': [85,None,45,None,67]}
df=pd.DataFrame(data)
print('Original Data')
df
df=df.dropna()
print('Dataset after dropna()')
df

Original Data
Dataset after dropna()

  Students  Marks
0    Ahmad   85.0
2    Intan   45.0
4    Akmal   67.0

In [14]:
emp_data={'Name':['Ahmad','Qaiyim','Intan','Fatehah','Khadijah','Sofea'],
         'Age':[26,None,25,10,34,None],
         'Salary':[5500,None,2400,4000,None,4500]}

df=pd.DataFrame(emp_data)
print('Original Data')
df

Original Data

       Name   Age  Salary
0     Ahmad  26.0  5500.0
1    Qaiyim   NaN     NaN
2     Intan  25.0  2400.0
3   Fatehah  10.0  4000.0
4  Khadijah  34.0     NaN
5     Sofea   NaN  4500.0

In [15]:
print(df.isnull().sum())

Name      0
Age       2
Salary    2
dtype: int64

In [16]:
df_drop=df.dropna()
df_drop

      Name   Age  Salary
0    Ahmad  26.0  5500.0
2    Intan  25.0  2400.0
3  Fatehah  10.0  4000.0

In [17]:
df_drop_salary=df.dropna(subset=['Salary'])
df_drop_salary

      Name   Age  Salary
0    Ahmad  26.0  5500.0
2    Intan  25.0  2400.0
3  Fatehah  10.0  4000.0
5    Sofea   NaN  4500.0

In [ ]:
df.fillna({'Age': df['Age'].mean(),'Salary': df['Salary'].mean()}, inplace=True)
df

In [20]:
emp_data={'Name':['Ahmad','Qaiyim','Intan','Fatehah','Khadijah','Sofea'],
         'Age':[26,None,25,10,34,None],
         'Salary':[5500,None,2400,4000,None,4500]}

df=pd.DataFrame(emp_data)
df.fillna({'Age': df['Age'].mean(),'Salary': df['Salary'].mean()}, inplace=True)
df

       Name    Age  Salary
0     Ahmad  26.00  5500.0
1    Qaiyim  23.75  4100.0
2     Intan  25.00  2400.0
3   Fatehah  10.00  4000.0
4  Khadijah  34.00  4100.0
5     Sofea  23.75  4500.0

# Downluad students_performance_dirty
## find out number of missing data
## drop rows where gender is missing
## fill study_hours with average study_hours

In [25]:
df=pd.read_csv('students_performance_dirty.csv')
print(df.head(5))

print('Missing Data')
print('Number of missing data: ', df.isnull().sum())

   gender  study_hours  attendance_pct  math_score  reading_score  final_score
0    male          1.7            83.6        62.0           91.0         38.9
1     NaN          2.6            91.2        82.0           60.0         37.5
2  female          2.9            97.5        69.0           57.0         35.0
3  female          4.8            85.7        78.0           62.0         36.5
4    male          3.9           -10.0        64.0           95.0         30.9
Missing Data
Number of missing data:  gender            8
study_hours       8
attendance_pct    0
math_score        0
reading_score     0
final_score       0
dtype: int64

In [41]:
df=pd.read_csv('students_performance_dirty.csv')
print(df.head(5))

# Solution for Question 1
print('\nMissing Data')
print('Number of missing data: ', df.isnull().sum())

#SOlution for Question 2
df=df.dropna(subset=['gender'])
print('\nNumber of missing data: ', df.isnull().sum())

avg_study_hours=df['study_hours'].mean()
df.fillna(avg_study_hours, inplace=True)
print('\nNumber of missing data: ', df.isnull().sum())

   gender  study_hours  attendance_pct  math_score  reading_score  final_score
0    male          1.7            83.6        62.0           91.0         38.9
1     NaN          2.6            91.2        82.0           60.0         37.5
2  female          2.9            97.5        69.0           57.0         35.0
3  female          4.8            85.7        78.0           62.0         36.5
4    male          3.9           -10.0        64.0           95.0         30.9

Missing Data
Number of missing data:  gender            8
study_hours       8
attendance_pct    0
math_score        0
reading_score     0
final_score       0
dtype: int64

Number of missing data:  gender            0
study_hours       7
attendance_pct    0
math_score        0
reading_score     0
final_score       0
dtype: int64

Number of missing data:  gender            0
study_hours       0
attendance_pct    0
math_score        0
reading_score     0
final_score       0
dtype: int64

In [46]:
df=pd.read_csv('students_performance_dirty.csv')
print(df.head(5))

# Solution for Question 1
print('\nMissing Data')
print('Number of missing data: ', df.isnull().sum())

#Solution for Question 2
df=df.dropna(subset=['gender'])
print('\nNumber of missing data: ', df.isnull().sum())

#Solution for question 3
df.fillna({'study_hours': df['study_hours'].mean()}, inplace=True)
print('\nNumber of missing data: ', df.isnull().sum())

   gender  study_hours  attendance_pct  math_score  reading_score  final_score
0    male          1.7            83.6        62.0           91.0         38.9
1     NaN          2.6            91.2        82.0           60.0         37.5
2  female          2.9            97.5        69.0           57.0         35.0
3  female          4.8            85.7        78.0           62.0         36.5
4    male          3.9           -10.0        64.0           95.0         30.9

Missing Data
Number of missing data:  gender            8
study_hours       8
attendance_pct    0
math_score        0
reading_score     0
final_score       0
dtype: int64

Number of missing data:  gender            0
study_hours       7
attendance_pct    0
math_score        0
reading_score     0
final_score       0
dtype: int64

Number of missing data:  gender            0
study_hours       0
attendance_pct    0
math_score        0
reading_score     0
final_score       0
dtype: int64