In [77]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
import numpy as np

In [78]:
# Collect the data
data=pd.read_csv('pass_fail.csv')
data.head()

   Hours Result
0      1   Fail
1      2   Fail
2      3   Fail
3      4   Pass
4      5   Pass

In [79]:
# Split the data
X = data[['Hours']]
y = data['Result']

In [80]:
# Create the model
model = LogisticRegression()

In [81]:
# Train the model
model.fit(X,y)

LogisticRegression()

In [84]:
hour_study=float(input('Enter your hours of study'))
our_result= pd.DataFrame([[hour_study]], columns=['Hours'])
predicted_value=model.predict(our_result)
print(f'After {hour_study} hours, you are likely to {predicted_value}')

Enter your hours of study 3

After 3.0 hours, you are likely to ['Fail']

In [86]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
import numpy as np

In [87]:
data=pd.read_csv('customer_purchase.csv')
data.head()

   Age  Salary Purchased
0   22   25000        No
1   25   30000        No
2   30   40000       Yes
3   35   50000       Yes
4   40   60000       Yes

In [88]:
# Split the data
le=LabelEncoder()
data['Purchased']= le.fit_transform(data['Purchased'])
X=data[['Age','Salary']]
y=data['Purchased']

In [89]:
data

   Age  Salary  Purchased
0   22   25000          0
1   25   30000          0
2   30   40000          1
3   35   50000          1
4   40   60000          1

In [90]:
# Crate the model
model=LogisticRegression()

# Train the model
model.fit(X,y)

LogisticRegression()

In [91]:
new_cust_age = int(input('Enter age'))
new_cust_sal = int(input('Enter your salary'))
our_cust= pd.DataFrame([[new_cust_age,new_cust_sal]], columns=['Age','Salary'])
prediction= model.predict(our_cust)
if (prediction):
    print('Purchased')
else:
    print('Not purchased')

Enter age 20
Enter your salary 70

Not purchased

In [95]:
new_customer=[[28,35000]]
our_customer= pd.DataFrame([[28,3500]], columns=['Age','Salary'])
prediction = model.predict(our_customer)
print(f'Predicted Result (1=Yes,0=No): {prediction[0]}')

Predicted Result (1=Yes,0=No): 0

# Logistic Regression - Spam/NoSpam
## Load the data
## Do the data cleaning and labelling (if required)
## Use Logistic Regression Algorithm to train the model
## Predict Result if the email is spam or not spam

In [112]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer

In [113]:
data=pd.read_csv('spam_dataset.csv')
data

                                       message_content  is_spam
0    Hello Lonnie,\n\nJust wanted to touch base reg...        0
1    Congratulations, you've won a prize! Call us n...        1
2    You have been pre-approved for a credit card w...        1
3    Limited time offer, act now! Only a few spots ...        1
4    Your loan has been approved! Transfer funds to...        1
..                                                 ...      ...
995  Hello Virginia,\n\nIt was great to catch up wi...        0
996  Final notice: Claim your inheritance from a di...        1
997  Hot singles in your area want to chat! Contact...        1
998  Your loan has been approved! Transfer funds to...        1
999  Dear Brian,\n\nI wanted to let you know about ...        0

[1000 rows x 2 columns]

In [118]:
X = data['message_content']
y = data['is_spam']

In [119]:
# Convert text to numbers
cv = CountVectorizer()
X_cv = cv.fit_transform(X)

In [120]:
model = LogisticRegression()

In [121]:
model.fit(X_cv,y)

LogisticRegression()

In [122]:
sample = ['Good Morning Qaiyim','We have shocking sales!']
predict = model.predict(cv.transform(sample))
if predict[0]:
    print('NOT SPAM')
else:
    print('SPAM')

NOT SPAM