# Example 2 Base Line (mean prediction)
## Data Cleaning & Preparation
## Linear Regression Model
## Find out MAE, RMSE, R-Squared
## Data set as follows

In [55]:
import numpy as np
import pandas as pd
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score,r2_score
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [56]:
data = {
    'Area':[850,900,1000,1100,1200,1500,1600,1800,2000],
    'Bedroom':[1,2,2,2,3,3,2,4,4],
    'Age': [1,1,3,2,1,2,2,1,2],
    'PriceIn100K':[5,6,7,7,7,9,9,11,None]
}
df = pd.DataFrame(data)
df

   Area  Bedroom  Age  PriceIn100K
0   850        1    1          5.0
1   900        2    1          6.0
2  1000        2    3          7.0
3  1100        2    2          7.0
4  1200        3    1          7.0
5  1500        3    2          9.0
6  1600        2    2          9.0
7  1800        4    1         11.0
8  2000        4    2          NaN

In [57]:
y = df['PriceIn100K']
y

0     5.0
1     6.0
2     7.0
3     7.0
4     7.0
5     9.0
6     9.0
7    11.0
8     NaN
Name: PriceIn100K, dtype: float64

In [58]:
df_filled = df.fillna({
    'PriceIn100K': df['PriceIn100K'].mean()
})
print(df_filled)

   Area  Bedroom  Age  PriceIn100K
0   850        1    1        5.000
1   900        2    1        6.000
2  1000        2    3        7.000
3  1100        2    2        7.000
4  1200        3    1        7.000
5  1500        3    2        9.000
6  1600        2    2        9.000
7  1800        4    1       11.000
8  2000        4    2        7.625

In [59]:
y = df_filled['PriceIn100K']
y

0     5.000
1     6.000
2     7.000
3     7.000
4     7.000
5     9.000
6     9.000
7    11.000
8     7.625
Name: PriceIn100K, dtype: float64

In [60]:
y_predict_baseline = np.repeat(y.mean(),len(y))
y_predict_baseline

array([7.625, 7.625, 7.625, 7.625, 7.625, 7.625, 7.625, 7.625, 7.625])

In [61]:
mae = mean_absolute_error(y,y_predict_baseline)
print(mae)

1.3611111111111112

In [62]:
mse = mean_squared_error(y, y_predict_baseline)
print(mse)

2.875

In [63]:
rmse = np.sqrt(mse)
print(rmse)

1.695582495781317

In [64]:
r2=r2_score(y,y_predict_baseline)
print('R-Squared Score is: ',r2)

R-Squared Score is:  0.0

In [65]:
print(df.isnull().sum())

Area           0
Bedroom        0
Age            0
PriceIn100K    1
dtype: int64

In [66]:
df = df.fillna(df.mean())
df

   Area  Bedroom  Age  PriceIn100K
0   850        1    1        5.000
1   900        2    1        6.000
2  1000        2    3        7.000
3  1100        2    2        7.000
4  1200        3    1        7.000
5  1500        3    2        9.000
6  1600        2    2        9.000
7  1800        4    1       11.000
8  2000        4    2        7.625

In [67]:
# Data prep, find input, output
X = df[['Area','Bedroom','Age']]
y = df['PriceIn100K']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.7,random_state=42)

In [68]:
model = LinearRegression()

In [69]:
model.fit(X_train,y_train)

LinearRegression()

In [70]:
y_predict = model.predict(X_test)
print(y_predict)

[ 9.8  6.2  8.6  6.  10.6  6.6  7.4]

In [71]:
mae = mean_absolute_error(y_test,y_predict)
print(mae)

0.9392857142857142

In [72]:
mse = mean_squared_error(y_test,y_predict)
print(mse)

1.6872321428571426

In [73]:
rmse = np.sqrt(mse)
print(rmse)

1.298935003322777

In [74]:
r2 = r2_score(y_test,y_predict)
print(r2)

0.4977064742737801