# 1. Base Line(mean prediction)
# 2. Data Cleaning & Preparation
# 3. Linear Regression
# 4. Features Engineering
# 5. Tunning
# 6. Cross Validation
# 7. Residual Analysis

In [18]:
import numpy as np
import pandas as pd
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score,r2_score
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [19]:
data = {
    'StudyHours': [2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Attendance': [60, 65, 70, 72, 75, 80, 85, 88, 90],
    'PrevScore': [40, 45, 50, 55, 60, 65, 70, 75, 80],
    'FinalMarks': [50, 55, 60, 65, 70, 75, 78, 85, 88]
}
df = pd.DataFrame(data)
df

   StudyHours  Attendance  PrevScore  FinalMarks
0           2          60         40          50
1           3          65         45          55
2           4          70         50          60
3           5          72         55          65
4           6          75         60          70
5           7          80         65          75
6           8          85         70          78
7           9          88         75          85
8          10          90         80          88

In [20]:
y = df['FinalMarks']
y

0    50
1    55
2    60
3    65
4    70
5    75
6    78
7    85
8    88
Name: FinalMarks, dtype: int64

In [21]:
y_predict_baseline = np.repeat(y.mean(),len(y))
y_predict_baseline

array([69.55555556, 69.55555556, 69.55555556, 69.55555556, 69.55555556,
       69.55555556, 69.55555556, 69.55555556, 69.55555556])

In [22]:
mae = mean_absolute_error(y,y_predict_baseline)
print(round(mae,2))

10.72

In [23]:
mse = mean_squared_error(y,y_predict_baseline)
print(round(mse,2))

154.02

In [24]:
rmse = np.sqrt(mse)
print(round(rmse,2))

12.41

In [25]:
# syntax
# r2=r2_score(actual_value,pedicted value)
# r-squared score is to check goodness to fit, it,s value lise 0 to 1, minus is very bad, its good as closer to 1
r2=r2_score(y,y_predict_baseline)
print('R-Squared Score is: ',r2)

R-Squared Score is:  0.0

In [26]:
print(f'Baseline MAE={mae:.2f}, RMSE={rmse:.2f}, R-Squared={r2:.2f}')

Baseline MAE=10.72, RMSE=12.41, R-Squared=0.00

In [27]:
# Clean the data
print(df.isnull().sum())

StudyHours    0
Attendance    0
PrevScore     0
FinalMarks    0
dtype: int64

In [28]:
df = df.fillna(df.mean())
df

   StudyHours  Attendance  PrevScore  FinalMarks
0           2          60         40          50
1           3          65         45          55
2           4          70         50          60
3           5          72         55          65
4           6          75         60          70
5           7          80         65          75
6           8          85         70          78
7           9          88         75          85
8          10          90         80          88

In [38]:
# Data prep, find input, output
X = df[['StudyHours','Attendance','PrevScore']]
y = df['FinalMarks']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [39]:
# Model Creation
model = LinearRegression()

In [40]:
model.fit(X_train,y_train)

LinearRegression()

In [41]:
y_predict = model.predict(X_test)
print(y_predict)

[83.23783784 55.16756757 73.92972973]

In [43]:
mae = mean_absolute_error(y_test,y_predict)
print(mae)

0.9999999999999952

In [46]:
mse = mean_squared_error(y_test,y_predict)
print(mse)

1.4262576089603038

In [47]:
rmse = np.sqrt(mse)
print(rmse)

1.1942602768912243

In [48]:
r2 = r2_score(y_test,y_predict)
print(r2)

0.9908312010852552